apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2022-12-08T16:15:51Z"
    generation: 1
    name: m9sweeper-webhook
    resourceVersion: "3058"
    uid: 3c8c6dac-344e-49b7-b8a9-ae8453cce91a
  webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lVZG03QlBNczhCYi8wRzIwMkhCRE9YZHlaNnlVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF3d1BUVGx6ZDJWbGNHVnlJRkJ5YjNoNU1CNFhEVEl5TVRJd09ERTJNVFUxTVZvWApEVEl6TURFd056RTJNVFUxTVZvd0dqRVlNQllHQTFVRUF3d1BUVGx6ZDJWbGNHVnlJRkJ5YjNoNU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdycncxQXNVWTRjZ2FQc2hpbkltcENsaFdjZmsKaGU3Q2hGSVphVi9wenpaWll0eEF3L1R4VXRyczNrNnIxWTBiUEdOQ25kRWRNaGhDSVhiWkpTNEwxU3hmME15Lwp6V2R6YlBtY24vTitlaWYwRWlJWEpCTG9PTjBYUzVJVlBKQzlKc0lwVXVpL2NSb2l3azRCeXp6Nk8rcUljQ2dECjRlM1E5b09GUmYvbWtRSUg5L09hU3lMWGhKV1l3emJ6ZmFtbEpnc1ZoOGJkK3RxOUxzaXArWlN4Sk83SlNNNEQKZmpZcWxNRFJsenJFTnNUdDlWd2c4OUVvT082OS9QdUVCVjBNaGdpRWRWbEdhVWV6MTExZXZYZXBnMTZDeXlSMgpldXllZmlpUUVmbXpoQzhJWVZBNXdRTEZmRDV5UkpQRGJHRWo2N3lHUytXUlBJaVFCMkRmZzR0NE9RSURBUUFCCm80R0ZNSUdDTUIwR0ExVWREZ1FXQkJTZ0VEeCsyajI3SStSL0p6bVlidUVPWjVkckp6QWZCZ05WSFNNRUdEQVcKZ0JTZ0VEeCsyajI3SStSL0p6bVlidUVPWjVkckp6QVBCZ05WSFJNQkFmOEVCVEFEQVFIL01DOEdBMVVkRVFRbwpNQ2FDSkcwNWMzZGxaWEJsY2kxd2NtOTRlUzV0T1hOM1pXVndaWEl0YzNsemRHVnRMbk4yWXpBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFVcjZacHp0S2xCZ3VRdFpPdkJiZE9mT2hiV3phZUJldUlVTkNFZmJkT0dvRmUwd24KdGhoZUhIU0FGcWt3SFNLdWVvdkQ4YnJKS1huNDI3R09TYmNtU1Q0cGVqL1hLU1BqTEFhN3lMblVtdEp1MXBYRgpSQUtPSGhhdXRyc3dzcE5pZVpRd3hGNDVqakFrNHB2dHlSWFgrd2FTUzM3dHBjRVM3OWsrU3VwMEt5TkdVUnVtCnNlOHVLNGJsbFpNZmJ2VzJUSkRRTXVSK1VZd3F3T2xCZG1rOWluRVlPbmh2N1RMcWUrbDdadEVQSENGR0dLd0gKdDhXSXZrcXRpck5LZkRHcnhWSGVuQ1ordGwxUEkyc0d5cXF6OFIyWmtEWXdET3NpVlIzM0FYcnJNYkQ1QWdOSApiSDRwYTBpMEpSbGZETStSQUl2M1pDaWZoWCtTRHBnTXlYeE1PQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: m9sweeper-proxy
        namespace: m9sweeper-system
        path: /api/clusters/1/validation
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: m9sweeper-validation-hook.m9sweeper.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - '*'
      apiVersions:
      - v1
      - v1beta1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
kind: List
metadata:
  resourceVersion: ""
